# Generated by Django 4.2.1 on 2023-06-04 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0002_subscriber"),
    ]

    operations = [
        migrations.CreateModel(
            name="Webhook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[("pitch_published", "Pitch submitted to review")],
                        default="pitch_published",
                        max_length=255,
                    ),
                ),
                ("url", models.URLField()),
                (
                    "publisher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="webhooks",
                        related_query_name="webhook",
                        to="backend.publisher",
                    ),
                ),
            ],
            options={
                "unique_together": {("action", "publisher")},
            },
        ),
    ]
