# Generated by Django 4.2.1 on 2023-06-12 08:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0005_alter_review_publisher"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pitch",
            name="platforms",
            field=models.ManyToManyField(blank=True, to="backend.platform"),
        ),
        migrations.AlterField(
            model_name="pitch",
            name="services",
            field=models.ManyToManyField(blank=True, to="backend.service"),
        ),
        migrations.AlterField(
            model_name="publisher",
            name="services",
            field=models.ManyToManyField(
                blank=True, through="backend.PublisherService", to="backend.service"
            ),
        ),
    ]
