# Generated by Django 4.2.1 on 2023-06-12 10:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0007_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="publisher",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
