# Generated by Django 4.2.1 on 2023-06-12 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0008_publisher_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="seen_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="publisher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="users",
                related_query_name="user",
                to="backend.publisher",
            ),
        ),
    ]
