# Generated by Django 4.2.1 on 2023-06-12 11:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0009_notification_seen_at_alter_user_publisher"),
    ]

    operations = [
        migrations.AlterField(
            model_name="abusereport",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="abusereport",
            name="resolved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="abusereport",
            name="resolved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="resolved_abuses",
                related_query_name="resolved_abuse",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="publisherservice",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
    ]
