# Generated by Django 4.2.1 on 2023-06-13 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0010_alter_abusereport_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="abusereport",
            name="pitch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="abuse_reports",
                related_query_name="abuse_report",
                to="backend.pitch",
            ),
        ),
    ]
