# Generated by Django 4.2.1 on 2023-06-22 16:19

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0011_alter_abusereport_pitch"),
    ]

    operations = [
        migrations.AddField(
            model_name="resolution",
            name="description",
            field=tinymce.models.HTMLField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="abusereport",
            name="description",
            field=tinymce.models.HTMLField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="pitch",
            name="description",
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name="publisher",
            name="description",
            field=tinymce.models.HTMLField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="publisherservice",
            name="description",
            field=tinymce.models.HTMLField(blank=True, default=""),
        ),
    ]
