# Generated by Django 4.2.1 on 2023-06-24 16:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "backend",
            "0012_resolution_description_alter_abusereport_description_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="pitch",
            name="is_abused",
            field=models.BooleanField(default=False),
        ),
    ]
