# Generated by Django 4.2.1 on 2023-06-24 16:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0013_pitch_is_abused"),
    ]

    operations = [
        migrations.AddField(
            model_name="pitch",
            name="is_resolved",
            field=models.BooleanField(default=False),
        ),
    ]
