"""
Django settings for reach4pitch project.

Generated by 'django-admin startproject' using Django 4.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import os


def _get_bool_setting(key: str, default="True") -> bool:
    val = os.getenv(key, default=default).lower()
    return val in {"1", "on", "t", "y", "true", "yes"}


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
_default_secret_key = (
    "django-insecure-4wu#4=2o*!zzi1!hya9u8k%10w+5t_%rcges(_k4+)e*2ppuoi"
)
SECRET_KEY = os.getenv(
    "RFORP_SECRET_KEY",
    default=_default_secret_key,
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _get_bool_setting("RFORP_DEBUG", default="True")

if not DEBUG and SECRET_KEY == _default_secret_key:
    raise ValueError("RFORP_SECRET_KEY not set")

if DEBUG:
    ALLOWED_HOSTS = []
else:
    ALLOWED_HOSTS = ["reach4pitch.com", "www.reach4pitch.com"]

SITE_ID = 1

# Application definition

INSTALLED_APPS = [
    "backend.apps.BackendConfig",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.flatpages",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",
    "django.contrib.sitemaps",
    "flags",
    "captcha",
    "django_rq",
    "tinymce",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "reach4pitch.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.template.context_processors.request",
                "django.contrib.messages.context_processors.messages",
                "backend.context_processors.auth",
                "backend.context_processors.notifications",
            ],
        },
    },
]

WSGI_APPLICATION = "reach4pitch.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases
DB_PASSWORD = os.getenv("RFORP_DB_PASSWORD")
if DEBUG:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }
else:
    if not DB_PASSWORD:
        raise ValueError("RFORP_DB_PASSWORD not set")
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": "reach4pitch",
            "USER": "reach4pitch",
            "PASSWORD": DB_PASSWORD,
            "HOST": "localhost",
            "PORT": "5432",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = "backend/static/"
# We don't have static outside of backend app
STATICFILES_DIRS = []
if DEBUG:
    STATICFILES_DIRS.append(os.path.join(BASE_DIR, STATIC_URL))

# Media (tinymce image uploads)
MEDIA_URL = "backend/media/"
if DEBUG:
    MEDIA_ROOT = os.path.join(BASE_DIR, MEDIA_URL)

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

AUTH_USER_MODEL = "backend.User"

# Email
FROM_EMAIL = os.getenv("RFORP_FROM_EMAIL", default="contact@reach4pitch.com")
EMAIL_HOST_PASSWORD = os.getenv("RFORP_SENDGRID_API_KEY")
if DEBUG:
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
else:
    if not EMAIL_HOST_PASSWORD:
        raise ValueError("RFORP_SENDGRID_API_KEY not set")
    EMAIL_HOST = "smtp.sendgrid.net"
    EMAIL_HOST_USER = "apikey"
    EMAIL_PORT = 587
    EMAIL_USE_TLS = True


# Auth
LOGIN_URL = "signup"
LOGIN_REDIRECT_URL = "backend:pitches_list"
LOGOUT_REDIRECT_URL = "backend:index"

FLAGS = {"LFP_ENABLED": [], "SIGNUP_ENABLED": []}

CAPTCHA_OUTPUT_FORMAT = "Captcha: %(hidden_field)s%(image)s<br>%(text_field)s<br><br>"

RQ_QUEUES = {
    "default": {
        "HOST": "localhost",
        "PORT": 6379,
        "DB": 0,
    },
}
if not DEBUG:
    STATIC_ROOT = "/var/www/reach4pitch/static/"
    MEDIA_ROOT = "/var/www/reach4pitch/media/"

if not DEBUG:
    LOGGING = {
        "version": 1,
        "disable_existing_loggers": False,
        "handlers": {
            "file": {
                "level": "DEBUG",
                "class": "logging.FileHandler",
                "filename": "/var/log/debug_reach4pitch.log",
            },
        },
        "loggers": {
            "django": {
                "handlers": ["file"],
                "level": "DEBUG",
                "propagate": True,
            },
        },
    }

if not DEBUG:
    STATICFILES_STORAGE = (
        "django.contrib.staticfiles.storage.ManifestStaticFilesStorage"
    )

TEST_RUNNER = "tests.runner.CustomDiscoverRunner"

_toolbar = (
    "undo redo",
    "formatselect",
    "bold italic",
    "alignleft aligncenter alignright alignjustify",
    "bullist numlist outdent indent",
    "image",
    "removeformat",
)

_plugins = (
    "lists",
    "image",
)

TINYMCE_DEFAULT_CONFIG = {
    "theme": "silver",
    "height": 500,
    "menubar": False,
    "images_upload_url": "/tinymce/upload_image/",
    "plugins": " ".join(_plugins).strip(),
    "toolbar": " | ".join(_toolbar).strip(),
    "init_instance_callback": "initEditorInstance",
}

TINYMCE_EXTRA_MEDIA = {
    "js": [
        "scripts/editor.js",
    ],
}
